### ISSUE TITLE
"AddToFavorites" option does not work when different tenant browse the super tenant's store

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/carbon-appmgt#704]
**Description:**
Steps to reproduce 
- Publish some public apps from super tenant
- Login to the carbon UI and create a new tenant
- Login to the tenant store (store/t/{tenant.domain.name}) using above created tenant.
- Now navigate to the super tenant's store.
- Tenant user can see the published app. Click on "Add to Favorites" option in the bottom right corner in the app icon.
- This will give error massage to user and can see following logs in backend.

TID: [] [] [2018-01-25 11:06:13,678] ERROR {org.wso2.carbon.appmgt.impl.dao.AppMDAO} -  Unable to get the WebApp ID for: APIIdentifier{providerName='app_mgt', apiName='HospiApp', version='1.0'} {org.wso2.carbon.appmgt.impl.dao.AppMDAO}
TID: [261] [] [2018-01-25 11:06:13,689] abc@abc8.com [261] [AppM]ERROR {JAGGERY.apis.favourite:jag} -  org.wso2.carbon.appmgt.api.AppManagementException: Unable to get the WebApp ID for: APIIdentifier{providerName='app_mgt', apiName='HospiApp', version='1.0'} {JAGGERY.apis.favourite:jag}

Same issue exists when removing already favorited app as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dinusha-dilrukshi** [comment]
Possible fix is available in https://github.com/dinusha-dilrukshi/carbon-appmgt-1/commit/d2ef747035dd62280cf0c960023709874edb3e8d

**Comment by GDRDABARERA** [comment]
Fixed with https://github.com/wso2/carbon-appmgt/commit/59691bf462074fedc9e14f254a1493ca2bf0b00f

**Comment by GDRDABARERA** [comment]
Hence Fixed, close the issue.
